Randomize left and right particle motion
JMS55/sandbox pull request #19
Opened 2022-06-14 22:06 UTC by henryksloan

Addresses `"Particles should move left/right randomly when they can do either"` from `todo.md`. The valid X positions for left/right particle motions are collected in a vector, which is then shuffled. If the shuffled vector is non-empty, an X position is selected and used.

This produces much more "correct" motion, especially for gasses; however, it makes it more apparent that they are randomized cellular automata. I would say that, if less "robotic" motion is desired, later changes can be made on top of this.

2022-06-16 04:38 UTC, JMS55 commented
Thanks for working on this!

I'm not sure I like how it looks for gasses. Powders and especially liquids are definitely an improvement though. I'd say we should merge it, regardless. Gasses have never been great anyways.

Could you write this to not allocate memory? It should be possible to have some kind of fixed-size array, or choose a random number depending on what options are available. Allocating a Vec for every particle every frame is pretty wasteful. You also don't have to shuffle the whole vector - just choose a random item from it.

2022-06-17 03:56 UTC, henryksloan commented
Good point, fixed. The new selector function is a bit verbose for clarity; I could cut it down if you want, at the possible cost of simplicity.

2022-06-19 16:18 UTC, JMS55 commented
Yeah, it's a bit too verbose imo. It needs to either be split up (if possible), or have comments explaining each branch. Other than that, and some minor nitpicks, I think this is good to go :)

2022-06-21 17:25 UTC, henryksloan commented
I just added some comments, as I think this new function makes sense as a unit.

2022-06-21 18:11 UTC, JMS55 requested changes

2022-06-24 15:47 UTC, henryksloan commented
Alright, all addressed.

In subsequent work, I think gasses can be improved by randomly choosing either up or up+side when both are possible, rather than preferring going upwards.

2022-06-26 16:32 UTC, JMS55 commented
Thanks, merged!

2022-06-26 16:33 UTC, merged